### ISSUE TITLE
SHM-2412: Faucet Docker

### ISSUE THREAD

**Issue by chrischabot** [shardeum-mirror/shardeum#185]
field | value
| - | - |
url | https://linear.app/shm/issue/SHM-2412/faucet-docker
author | @
date | Tue Aug  8 18:22:52 BST 2023
state | Needs Review
project | Ops Strike Team
priority | No priority
assignee | @
labels | Migration
related | 
parent | 
children | 
PRs | 
attachments | 

We should create a few tags so that we can run:

prod: twitter + discord docker

```
(I assume prod will require someone to log in and do some manual setup as well, we don’t have to solve this to be 100% automatic since I assume that may not be worth the time payoff just yet)
```

basic: we can push an old branch of the faucet up for this one that has less permissions . Useful for quickly setting up hackathons.

Of the two I would even be ok that we just start with the “basic” docker and just make this task easy on ourselves because that is what will pay off quickly for hackathons or dev networks that we share with other parties (I see some use in this)

**Comment by chrischabot** [comment]
field | value
|-|-|
url | https://linear.app/shm/issue/SHM-2412/faucet-docker#comment-8458b0ef
author | @
date | Fri Dec 29 13:55:40 GMT 2023

builded docker image locally, will do test it, once done with testing, will push the docker image to gitlab container registry

**Comment by chrischabot** [comment]
field | value
|-|-|
url | https://linear.app/shm/issue/SHM-2412/faucet-docker#comment-8659f4a4
author | @
date | Tue Jan  2 04:57:49 GMT 2024

pushed faucet docker image with tag `registry.gitlab.com/shardeum/faucet-server:main-4a1094a`

**Comment by chrischabot** [comment]
field | value
|-|-|
url | https://linear.app/shm/issue/SHM-2412/faucet-docker#comment-9da299bb
author | @
date | Tue Jan  2 04:59:37 GMT 2024

Here's the docker-compose.yaml, (mounting `.env`and `config.json` file externally will require faucet-server to recompile which can be put in like below)

```
version: "3.8"
services:
  faucet:
    image: registry.gitlab.com/shardeum/faucet-server:main-4a1094a
    ports:
      - 3000:3000
    volumes:
      - ./faucet-server/.env:/app/faucet-server/.env
      - ./faucet-server/src/config.json:/app/faucet-server/src/config.json
    entrypoint: /bin/bash
    command:
      - -cex
      - |
        cd /app/faucet-server
        npm run compile
        npm start
```
