### ISSUE TITLE
SHM-2242: Secret scanning in Shardeum repos

### ISSUE THREAD

**Issue by chrischabot** [shardeum-mirror/shardeum#239]
field | value
| - | - |
url | https://linear.app/shm/issue/SHM-2242/secret-scanning-in-shardeum-repos
author | @
date | Tue Aug  8 21:13:19 BST 2023
state | Done
project | Security Grab bag
priority | Medium
assignee | @
labels | 
related | 
parent | 
children | 
PRs | 
attachments | 

# To-do

* \[x\] identify effective secret scanning solution
* \[ \] identify repos that need scanning
  * \[ \] Can be done for all open-sourced repositories IMO but needs discussion
* \[ \] create tickets to implement
  * \[ \] Needs discussion\\

# Steps to enable secret scanning for a repository

1. Locally install Yelp/detect-secrets using one of steps mentioned in `[https://github.com/Yelp/detect-secrets](https://github.com/Yelp/detect-secrets)`
2. Run the command `detect-secrets scan --exclude-files .git/ > .secrets.baseline` to get a report of all likely secrets in the repository
3. Audit the file for false positives using the command `detect-secrets audit .secrets.baseline`
4. Add a new stage or a new `gitlab-ci.yml` file in the project with the following

   ```
   stages:
     - detect-secrets
   
   detect-secrets:
     image: python:3.9
     stage: detect-secrets
     script:
       - pip install detect-secrets
       - detect-secrets scan --exclude-files .git/ --baseline .secrets.baseline
       - detect-secrets audit .secrets.baseline
     allow_failure: true
   
   ```
5. Push the .secrets.baseline and the gitlab-ci.yml changes to remote
6. Sample integration: [https://gitlab.com/shardeum/validator/cli/-/merge_requests/35/diffs](https://gitlab.com/shardeum/validator/cli/-/merge_requests/35/diffs)
